services:
  notatex-app:
    build:
      context: ./notatex-app
      dockerfile: Dockerfile
    ports:
      - "5050:80"
  notatex-front:
    build:
      context: ./front/notatex
      dockerfile: Dockerfile

    ports:
      - "8080:3000"
networks:
  default:
    driver: bridge
    external: false
