services:
  notatex-db:
    image: postgres
    environment:
      - POSTGRES_USER=notatex
      - POSTGRES_PASSWORD=notatex
  notatex-app:
    depends_on:
      - notatex-db
    build:
      context: ./notatex-app
      dockerfile: Dockerfile
    ports:
      - "5050:8080"
  notatex-front:
    build:
      context: ./front/notatex
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
networks:
  default:
    driver: bridge
    external: false
